name = "Tentacle Flavoured"
author = "Octelly"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf7c5171baf1dd206216bd8c1aadc0337b551f630a57615c953305a9b92ac61c"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
