name = "Tentacle Flavoured"
author = "Octelly"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28cbce2d2199c1ebdc57d31487669a77ec1154af9afab267fb7a5a63d7fac616"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
