name = "Tentacle Flavoured"
author = "Octelly"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3e2366e1d21b91bd7cedd94f33644624fba05b9188d18c82105202bb31ea5bd"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
