name = "Tentacle Flavoured"
author = "Octelly"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5541289359cd7195e75d42b9e1a1dba73a5f7f4e48f777fbed715cad83613872"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
