name = "Tentacle Flavoured"
author = "Octelly"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2079f36178d4d6d6b1cb268ecfee4f8a694aa414be65c3f2507ade7c08d0a94"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
