name = "Tentacle Flavoured"
author = "Octelly"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71b1c7238031a5d932475aa6d30a87c8c33751e3562f6743fed31a2c249e08ad"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
