name = "Tentacle Flavoured"
author = "Octelly"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "619c1697716216256c227fd120541f4c46b6352dafc5c3f5e41b9b4fee84002b"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
