name = "Tentacle Flavoured"
author = "Octelly"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdbf81d53d16df9fc78b90c8ec8dad6cc6ea9ca420c87567acb16c2689086373"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
