name = "Tentacle Flavoured"
author = "Octelly"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "871b6a9a7da13acfea58013af98da72a4f9f54528711d6e0908675aab9ace8e1"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
