
#.
#Enable/disable features
[features]
	#.
	copycat_vertical_step = true
	six_way_gearbox = false
	encased_chain_cogwheel = false
	inverted_clutch = false
	empty_fan_catalyst = false
	parallel_gearbox = false
	freewheel_clutch = false
	shear_pin = false
	inverted_gearshift = false
	centrifugal_clutch = false
	copycat_slab = true
	overstress_clutch = false
	brake = false
	copycat_block = true
	copycat_beam = true
	brass_gearbox = false

